const path_name = {
    dashboard: '/dashboard',
    forgot_password: '/quen-mat-khau',
    logout: '/dang-xuat',
    // sell: '/ban-hang',
    login: '/',
    change_password: '/doi-mat-khau',
    product: '/san-pham',
    brand: '/thuong-hieu',
    color: '/mau-sac',
    category: '/loai-san-pham',
    material: '/chat-lieu',
    supplier: '/nha-cung-cap',
    size: '/kich-thuoc',
    club: '/cau-lac-bo',
    newSell: '/hoa-don',
    order: '/don-hang',
    orderDetail: '/orderdetail',
    orderView: '/orderview',
    user: '/tai-khoan',
    role: '/vai-tro',
    voucher: '/giam-gia',
};

export default path_name;
