const path_name = {
    dashboard: '/dashboard',
    forgot_password: '/quen-mat-khau',
    logout: '/dang-xuat',
    login: '/',
    change_password: '/doi-mat-khau',
    product: '/san-pham',
    add_product: '/them-san-pham',
    edit_product: '/sua-san-pham',
    brand: '/thuong-hieu',
    color: '/mau-sac',
    category: '/loai-san-pham',
    material: '/chat-lieu',
    supplier: '/nha-cung-cap',
    size: '/kich-thuoc',
    club: '/cau-lac-bo',
    newSell: '/ban-hang',
    order: '/don-hang',
    sell: '/chi-tiet-don-hang',
    order_detail: '/order-detail',
    user: '/tai-khoan',
    role: '/vai-tro',
    voucher: '/giam-gia',
};

export default path_name;
